//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Навчальна_практика_Гута.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public decimal DiscountedPrice { get; set; }
        public string BuyerFirstName { get; set; }
        public string BuyerLastName { get; set; }
        public int BuyerId { get; set; }
        public Nullable<int> DiscountId { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
